-- vim.g.coq_settings = {
--   auto_start = 'shut-up',
--   clients = {
--     tree_sitter = { enabled = false },
--     buffers = { enabled = false },
--     paths = { preview_lines = 3 }
--   },
--   display = { icons = { mode = 'short' } },
--   keymap = { recommended = true },
-- }
